openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://pandaserver.cern.ch
    description: Optional server description, e.g. Main (production) server

paths:
